name: Biiit
favicon: null
layout_spectrum: 0.87913
typography_spectrum: 0.09277
title: Beat Meier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#c2cacc'
    - '#899aa4'
    - '#415065'
    - '#e3873e'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
